Changed code header
Pelagicore/bluetooth-demo pull request #1
Opened 2017-08-10 02:44 UTC by jeremiah

SPDX-ification.

2017-08-10 06:09 UTC, breakreturn requested changes

2017-08-10 06:09 UTC, breakreturn commented on plugin.cpp
> + */
This doesn't really look like the template example we have does it? https://github.com/Pelagicore/OpenSourceTemplates/blob/master/examples/Example_header_cpp_mpl.md

2017-08-10 06:09 UTC, breakreturn commented on plugin.cpp
> + * SPDX-License-Identify: MPL-2.0
Should this be "SPDX-License-Identifier" ?

2017-08-10 06:11 UTC, jonte requested changes
Hi Jeremiah,

Thanks for the patch.

I would prefer to format the file headers in the following way: https://github.com/Pelagicore/bluetooth-demo/blob/master/bluephonebook.cpp#L6

As in, include the short version of the license text, and leave the SPDX identifier out (the license analysys tools select the correct license anyway based on the license header).

Will you change your patch?

2017-08-10 06:13 UTC, jonte commented on plugin.cpp
> + */
Ah. I wasn't aware of this example file when I wrote my previous comment. If there is a standard within the company, then we should follow it. I would argue that this standard can be improved though (same arguments as my previous comment).

2017-08-10 06:42 UTC, breakreturn commented on plugin.cpp
> + */
@jonte The templates are there to be the "current truth" so to speak. I.e. they enable us to not have the same discussions every time we create a new code file, but they are also intended to be improved over time when anyone have good input.

2017-08-10 06:43 UTC, jonte commented on plugin.cpp
> + */
I will open a discussion on the template file on GitHub, and we can discuss how it should look in that thread.

2017-08-10 10:46 UTC, DunderRoffe approved these changes
Given that the concerns of @breakreturn and @jonte are addressed I approve this change.

2017-08-11 02:17 UTC, jeremiah commented
I'm going to close this PR. I'll create a new PR that follows the policy we agreed to and that is published in the Software Factory documentation.

2017-08-11 02:17 UTC, closed without merging